# Generated by Django 4.2.3 on 2023-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('PK_attendance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('FK_emp_id', models.IntegerField()),
                ('FK_showroom_id', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Login_Time', models.DateTimeField()),
                ('Logout_Time', models.DateTimeField(default=None, null=True)),
                ('islate', models.BooleanField(default=None, null=True)),
                ('IsExcused', models.BooleanField(default=None, null=True)),
                ('IsNotPresent', models.BooleanField(default=False)),
                ('Remarks', models.CharField(default=None, max_length=100, null=True)),
                ('TransID', models.CharField(default=None, max_length=100, null=True)),
                ('ISDELETED', models.BooleanField(default=None, null=True)),
                ('FK_USER_DATE_SHIFT_ID', models.CharField(default=None, max_length=100, null=True)),
                ('FK_emp_id1', models.CharField(default=None, max_length=100, null=True)),
                ('fk_emp_code', models.CharField(default=None, max_length=100, null=True)),
                ('fk_branch_code', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginLogout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_emp_id', models.IntegerField()),
                ('Login_Time', models.TimeField()),
                ('Logout_Time', models.TimeField(default=None, null=True)),
                ('fk_emp_code', models.CharField(default=None, max_length=100, null=True)),
                ('Late_Time', models.TimeField(default=None, null=True)),
                ('Working_hours', models.TimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
